FT2023-341: Addition of the files for configform module .
Arijit-Acharya-innoraft/Custom_Module pull request #2
Opened 2023-07-06 19:02 UTC by Arijit-Acharya-innoraft

2023-07-11 13:31 UTC, vivekpan27 commented on web/modules/custom/configform/configform.info.yml
> +type: 'module'
Should this be in quotes?
Same for other values.

2023-07-11 13:34 UTC, vivekpan27 requested changes

2023-07-11 13:34 UTC, vivekpan27 commented on web/modules/custom/configform/src/Form/CustomConfigForm.php
> +    return 'configform.settings';
Please check if we use `.` in form id.

2023-07-11 13:34 UTC, vivekpan27 commented on web/modules/custom/configform/src/Form/CustomConfigForm.php
> +  public function buildForm(array $form, FormStateInterface $form_state) {
Are you sure you need to add such extensive function docblock for an inherited function?
Same for the other function.

2023-07-11 13:34 UTC, vivekpan27 commented on web/modules/custom/configform/config/install/configform.settings.yml
Config schema file is missing.

2023-07-11 13:34 UTC, vivekpan27 commented on web/modules/custom/configform/config/install/configform.settings.yml
> +  - Male
Why are all the fields arrays instead of being string?

2023-07-12 10:50 UTC, vivekpan27 commented on web/modules/custom/configform/config/install/configform.settings.yml
Still missing.

2023-07-12 10:50 UTC, vivekpan27 commented on web/modules/custom/configform/config/install/configform.settings.yml
> +  - Male
Why is this an array?

2023-07-12 14:46 UTC, vivekpan27 commented
PR is ok.
But default configuration is missing.
Please check how to add default configuration to a module.

2023-07-13 05:55 UTC, Arijit-Acharya-innoraft commented
The file exists.

2023-07-13 15:25 UTC, vivekpan27 approved these changes

2023-07-13 15:25 UTC, vivekpan27 commented
Nice, clean PR.

2023-07-13 15:25 UTC, merged